import java.util.Scanner;

public class Main
{
	public static void main(String[] args) {
	float salarioMin,funcSal,salsMins;
	Scanner teclado = new Scanner (System.in);
	    
	System.out.print("Informe o valor do salario minimo:");
	salarioMin = teclado.nextFloat();
	    
	System.out.print("Informe o valor do salario do funcionario:");
	funcSal = teclado.nextFloat();
	    
	salsMins = funcSal/salarioMin;
         
   System.out.printf("O funcionário recebe %.1f", +salsMins);
   System.out.print(" salários mínimos");
	    
	}
	    
}
