import java.util.Scanner;

 public class Main
    {
        public static void main (String[] args) {

            Scanner teclado = new Scanner(System.in);
            
            int frangos,valor;
            
            System.out.print("Digite a QTDE de frangos: ");
            frangos = teclado.nextInt();
            
            System.out.print("\n");
            
            valor = frangos * 11;
            
            System.out.print("O valor total para identificar os frangos e : R$" +valor);
          
            }
    
    }
